### ISSUE TITLE
How Do You Generate the DTMF Tone Once or for a specified duration?

### ISSUE THREAD

**Issue by eopeter** [palmerc/DTMFSounds#2]
Current Code generates the code infinitely or so it seems. How can I generate the code one time only?

Thanks

**Comment by palmerc** [comment]
Did you see:

    _player.scheduleBuffer(buffer, at:nil, options:.loops, completionHandler: nil)

Replace it with:

    _player.scheduleBuffer(buffer, at:nil, completionHandler: nil)

**Comment by eopeter** [comment]
Ahh, I saw that line but didn't think to remove the option parameter completely. Thanks!!!

**Comment by palmerc** [comment]
You can also pass a Raw value of zero to options
